server:
  port: 8081 # dfeault 8080
  
spring:
  application:
    name: user-service
  profiles:    active: test
  cloud:    config:      #uri: http://localhost:8888
      discovery:        enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: users
    password: p4ssw0rd
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  aop:
    auto: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:  endpoints:    web:      exposure:        include: "*"