server:
  port: 8081 # dfeault 8080
  
spring:
  application:
    name: user-service
  profiles:    active: test

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:  endpoints:    web:      exposure:        include: "*"