#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
        
spring:
  profiles:
    active: test
  cloud:
    config:
      uri: http://localhost:${config.port:8888}
  application:
    name: user-service
#  datasource:
#    url: ${db_url}
#    username: ${db_username}
#    password: ${db_pass}
#    
#eureka:
#  client:
#    service-url:
#      defaultZone: ${eureka_url}